### ISSUE TITLE
Updated MiniIndy Photos page

### ISSUE THREAD

**Issue by HilkiahMakemo** [skywestairlines/www.miniindy.org#17]
http://www.miniindy.org/miniindy-media/miniindy-photos

**Comment by HilkiahMakemo** [comment]
We have decided to go with http://www.miniindy.org/miniindy-media/images/ instead

**Comment by dechasse** [comment]
@HilkiahMakemo I believe we can close this issue, however note that issue #24 is still active and needs to be done at some point.
